In [14]:
#trial and error
import numpy as np
w1=int(input("Enter weight 1: "))
w2=int(input("Enter weight 2: "))
w=[w1,w2]
coord=[[x,y] for x in range(2) for y in range(2)]
print(coord)
orgate=[(x,y) (x or y) for r in coord] 

eff=0
i=0
for r in coord:
    z=np.dot(r,w)
    if z>0:
        out=1
    else:
        out=0
    if out==orgate[i]:
        eff=eff+1
    i=i+1
per=(eff/4)*100
print("Efficiency:",per,"%")

<>:7: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
<>:7: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?


Enter weight 1: 2
Enter weight 2: 3
[[0, 0], [0, 1], [1, 0], [1, 1]]


C:\Users\91960\AppData\Local\Temp\ipykernel_4792\3249692102.py:7: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
  orgate=[(x,y) (x or y) for r in coord]
C:\Users\91960\AppData\Local\Temp\ipykernel_4792\3249692102.py:7: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
  orgate=[(x,y) (x or y) for r in coord]
C:\Users\91960\AppData\Local\Temp\ipykernel_4792\3249692102.py:7: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
  orgate=[(x,y) (x or y) for r in coord]
C:\Users\91960\AppData\Local\Temp\ipykernel_4792\3249692102.py:7: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
  orgate=[(x,y) (x or y) for r in coord]


NameError: name 'x' is not defined

In [ ]:
#answer
import numpy as np
w1=int(input("Enter weight 1: "))
w2=int(input("Enter weight 2: "))
w=[w1,w2]
coord=[(x,y) for x in range(2) for y in range(2)]
print(coord)
orgate=[0,1,1,1]

eff=0
i=0
for r in coord:
    z=np.dot(r,w)
    if z>0:
        out=1
    else:
        out=0
    if out==orgate[i]:
        eff=eff+1
    i=i+1
per=(eff/4)*100
print("Efficiency:",per,"%")

In [ ]:

import numpy as np
w1=int(input("Enter weight 1: "))
w2=int(input("Enter weight 2: "))
bias=int(input("Enter bias: "))
w=[w1,w2]
coord=[(x,y) for x in range(2) for y in range(2)]
print(coord)
andgate=[0,0,0,1]

eff=0
i=0
for r in coord:
    z=(np.dot(r,w)+bias)
    if z>0:
        out=1
    else:
        out=0
    if out==andgate[i]:
        eff=eff+1
    i=i+1
per=(eff/4)*100
print("Efficiency:",per,"%")

In [ ]:

import numpy as np
w1=int(input("Enter weight 1: "))
w2=int(input("Enter weight 2: "))
bias=int(input("Enter bias: "))
w=[w1,w2]
coord=[(x,y) for x in range(2) for y in range(2)]
print(coord)
andgate=[0,0,0,1]

eff=0
i=0
for r in coord:
    z=(np.dot(r,w)+bias)
    if z>0:
        out=1
    else:
        out=0
    if out==andgate[i]:
        eff=eff+1
    i=i+1
per=(eff/4)*100
print("Efficiency:",per,"%")

In [ ]:

import numpy as np
w1=int(input("Enter weight 1: "))
w2=int(input("Enter weight 2: "))
bias=int(input("Enter bias: "))
w=[w1,w2]
coord=[(x,y) for x in range(2) for y in range(2)]
print(coord)
andgate=[0,0,0,1]

eff=0
i=0
for r in coord:
    z=(np.dot(r,w)+bias)
    if z>0:
        out=1
    else:
        out=0
    if out==andgate[i]:
        eff=eff+1
    i=i+1
per=(eff/4)*100
print("Efficiency:",per,"%")

In [16]:

import numpy as np
w1=int(input("Enter weight 1: "))
w2=int(input("Enter weight 2: "))
bias=int(input("Enter bias: "))
w=[w1,w2]
coord=[(x,y) for x in range(2) for y in range(2)]
print(coord)
norgate=[1,0,0,0]

eff=0
i=0
for r in coord:
    z=(np.dot(r,w)+bias)
    if z>0:
        out=1
    else:
        out=0
    if out==norgate[i]:
        eff=eff+1
    i=i+1
per=(eff/4)*100
print("Efficiency:",per,"%")

Enter weight 1: -5
Enter weight 2: -4
Enter bias: 1
[(0, 0), (0, 1), (1, 0), (1, 1)]
Efficiency: 100.0 %


In [36]:
#NAND Gate
import numpy as np
w1=int(input("Enter weight 1: "))
w2=int(input("Enter weight 2: "))
bias=int(input("Enter bias: "))
w=[w1,w2]
coord=[(x,y) for x in range(2) for y in range(2)]
print(coord)
nandgate=[1,1,1,0]

eff=0
i=0
for r in coord:
    z=(np.dot(r,w)+bias)
    if z>0:
        out=1
    else:
        out=0
    if out==nandgate[i]:
        eff=eff+1
    i=i+1
per=(eff/4)*100
print("Efficiency:",per,"%")

Enter weight 1: -4
Enter weight 2: -3
Enter bias: 6
[(0, 0), (0, 1), (1, 0), (1, 1)]
Efficiency: 100.0 %


enter weight 1 value:2
enter weight 2 value:3
[(0, 0), (0, 1), (1, 0), (1, 1)]
[1, 0, 0, 0]
Efficiency: 0.0 %


In [5]:
import numpy as np
bias=int(input("Enter Bias:"))
w=[0,0,bias]
exout=[1,-1,1]
n=int(input("enter no. of elements:"))
l=[]
m=0
def checkmis(l,co):
    for i in l:
        if l[i]==co[i]:
            m+=1

for i in range(0,n):
    ele=[int(input()),int(input()),int(input())]
    l.append(ele)
print(l)
for i in l:
    x=np.dot(i,w)
    if int(x)*int(w[i])<=0:
        w=w+np.dot(w,(int(w[i])*i))
        m+=1
    
    
     
        

Enter Bias:2
enter no. of elements:2
1
2
3
4
5
6
[[1, 2, 3], [4, 5, 6]]


TypeError: list indices must be integers or slices, not list

In [1]:
import numpy as np
x=[[2,1,1],[-1,4,1],[3,2,1]]
x=np.array(x)
w=[0,0,1]
w=np.array(w)
out=[1,-1,1]

m=0

def checkmis(l,eo,m):
    if l[i]!=eo[i]:
        m+=1
    return m

def checkweight(x,w):
    l=[]
    for i in range(len(x)):
        y=np.dot(x[i],w)
        l.append(y)
    return l
    #print(l)   
for i in range(len(x)):
    y=np.dot(x[i],w)
    if y!= out[i]:
        m+=1

print(m)

while(m>0):
    if checkmis(checkweight(x,w),out,m)<0:
        w=w+()
        
    
    
    

1
[1, 1, 1]


TypeError: 'NoneType' object is not subscriptable

In [4]:
import numpy as np

# Given data points as a numpy array
data_points = np.array([[3, 1, 1], [1, 0, -1], [1.5, 0, -1], [4, 1, 1], [-2, 0, -1], [6, 1, 1]])

# Initialize weights to zeros (excluding the bias term)
weights = np.zeros(data_points.shape[1] - 1)

learning_rate = 1
max_epochs = 1000

for epoch in range(max_epochs):
    misclassified = False
    
    for point in data_points:
        xi = point[:-1]  # Extract the coordinates
        yi = point[-1]   # Extract the label

        if yi * np.dot(weights, xi) <= 0:
            weights += learning_rate * yi * xi
            misclassified = True
            
    if not misclassified:
        print("Converged in", epoch + 1, "epochs.")
        break

if misclassified:
    print("Max epochs reached. The algorithm did not converge.")

print("Weights:", weights)


Max epochs reached. The algorithm did not converge.
Weights: [0.5 7. ]


In [8]:

import numpy as np
w1=int(input("Enter weight 1: "))
w2=int(input("Enter weight 2: "))
bias=int(input("Enter bias: "))
w=[w1,w2]
coord=[(x,y) for x in range(2) for y in range(2)]
print(coord)
nandgate=[1,1,1,0]

eff=0
i=0
for r in coord:
    z=(np.dot(r,w)+bias)
    if z>0:
        out=1
    else:
        out=0
    if out==nandgate[i]:
        eff=eff+1
    i=i+1
per=(eff/4)*100
print("Efficiency:",per,"%")

Enter weight 1: -2
Enter weight 2: -3
Enter bias: 4
[(0, 0), (0, 1), (1, 0), (1, 1)]
Efficiency: 100.0 %


In [31]:

import numpy as np

x1 = np.array([3, 1])
x2 = np.array([1, 0])
x3 = np.array([1.5, 0])
x4 = np.array([4, 1])
x5 = np.array([-2, 0])
x6 = np.array([6, 1])

x = np.array([x1, x2, x3, x4, x5, x6])
wt = [0, 0, 1]
eo = [1, -1, -1, 1, -1, 1]
co = []
c = [0,0,0,0,0,0]
a = 0
n = -1
m = 0

#pre-processing array
x1 = np.append(x1, 1)
x2 = np.append(x2, 1)
x3 = np.append(x3, 1)
x4 = np.append(x4, 1)
x5 = np.append(x5, 1)
x6 = np.append(x6, 1)
x = np.array([x1, x2, x3, x4, x5, x6])

#while loop
while(n < 0):
    if (co == eo):
        n = 1
    for i in range(len(eo)):
        c[i] = np.dot(x[i], wt)
        #print(c[i])
        if (c[i] > 0):
            co.append(1)
        else:
            co.append(-1)
    print(co)
    if (co == eo):
        n = 1
    else:
        for i in range(6):
            if eo[i] != co[i]:
                print(i)
                a = i
                break
    wt = wt + (eo[a] * x[a])
    co = []
    m = m + 1

print("Total Iterations : ", m)   
print("final Weight is : ", wt)


[1, 1, 1, 1, 1, 1]
1
[-1, -1, -1, -1, 1, -1]
0
[1, 1, 1, 1, -1, 1]
1
[1, 1, 1, 1, -1, 1]
1
[-1, -1, -1, -1, -1, -1]
0
[1, 1, 1, 1, -1, 1]
1
[1, 1, 1, 1, -1, 1]
1
[1, -1, -1, 1, -1, 1]
Total Iterations :  8
final Weight is :  [ 0.  2. -3.]


In [34]:
import numpy as np
#Data points input
x = np.array([
    [3, 1, 1],
    [1, 0, 1],
    [1.5, 0, 1],
    [4, 1, 1],
    [-2, 0, 1],
    [6, 1, 1]
])

wt = np.array([0, 0, 1]) #initial weight
expout = np.array([1, -1, -1, 1, -1, 1]) #expected output
calout = np.empty_like(expout) #initialising calculated output
a = 0 #misclassified index 
n = -1 # terminating variable of while loop
m = 0 #No of iterations

#While loop
while n < 0:
    calout = np.empty_like(expout)
    for i in range(len(expout)):
        c = np.dot(x[i], wt)
        calout[i] = 1 if c > 0 else -1
    print(calout)
    if np.array_equal(calout, expout): #if equal n=1 and terminates
        n = 1
    else: 
        for i in range(6):
            if expout[i] != calout[i]: 
                print(i)
                a = i
                break
        wt = wt + (expout[a] * x[a]) #updating weight if not equal
    m = m + 1

print("Total No. of Iterations:", m)
print("Final Updated Weight:", wt)


[1 1 1 1 1 1]
1
[-1 -1 -1 -1  1 -1]
0
[ 1  1  1  1 -1  1]
1
[ 1  1  1  1 -1  1]
1
[-1 -1 -1 -1 -1 -1]
0
[ 1  1  1  1 -1  1]
1
[ 1  1  1  1 -1  1]
1
[ 1 -1 -1  1 -1  1]
Total Iterations: 8
Final Weight: [ 1.  2. -2.]


In [39]:
#NOR GATE 
import numpy as np
w1=int(input('enter weight 1:'))
w2=int(input('enter weight 2:'))
w=[w1,w2]
coord=[(x,y) for x in range(2) for y in range(2)]#list comprehension
print(coord)
norgate=[1,0,0,0]


eff=0
i=0
for r in coordinates:
    z=np.dot(r,w)
    if z>0:
        out=0
    else:
        out=1
        
    if out==norgate[i]:
        eff=eff+1
    i=i+1
    
per=(eff/4)*100
print("Efficiency:",per,"%")

enter weight 1:4
enter weight 2:5
[(0, 0), (0, 1), (1, 0), (1, 1)]
Efficiency: 100.0 %


In [5]:
import numpy as np

X = np.array([[0.25, 0.353],
              [0.25, 0.471],
              [0.5, 0.353],
              [0.5, 0.647],
              [0.75, 0.705],
              [0.75, 0.882],
              [1, 0.705],
              [1, 1]])


y = np.array([0, 1, 0, 1, 0, 1, 0, 1])


w = np.zeros(X.shape[1])
b = 0

learning_rate = 0.1

epochs = 100  

for _ in range(epochs):
    for i in range(len(X)):
        z = np.dot(X[i], w) + b
        output = 1 if z >= 0 else 0
 
        
        w += learning_rate * (y[i] - output) * X[i]
        b += learning_rate * (y[i] - output)


print("Final weights:", w)
print("Final bias:",b)

Final weights: [-0.525   0.9168]
Final bias: -0.30000000000000004
